name: Advance CI/CD workflow

on:
    push:
        branches: ['main']
        paths-ignore:
            - 'readme.md'
            - '.gitignore'

    pull_request: 
        branches: ['main']
        paths-ignore:
            - 'readme.md'
            - '.gitignore'

# making sure the running workflow is not deleted by a new push/pr
concurrency:
    group: 'first'
    cancel-in-progress: false

jobs:
    build:
        runs-on: ubuntu-latest
        steps:

            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                java-version: '17'
                distribution: 'temurin'
                cache: maven

            - name: Build with Maven
              run: mvn -B package --file pom.xml

            - name: Making the .jar file into an artifact
              uses: actions/upload-artifact@v4
              with:
                name: maven-artifact
                path: target/*.jar

    security_checks:
        needs: build
        runs-on: ubuntu-latest
        steps:

            - name: Downloading the maven artifact made in the previous job
              uses: actions/download-artifact@v4
              with:
                name: maven-artifact

            - name: Checking out the artifact
              run: ls -ltr