name: Advance CI/CD workflow

on:
    push:
        branches: ['main']
        paths-ignore:
            - 'readme.md'
            - '.gitignore'

    pull_request: 
        branches: ['main']
        paths-ignore:
            - 'readme.md'
            - '.gitignore'

# making sure the running workflow is not deleted by a new push/pr
concurrency:
    group: 'first'
    cancel-in-progress: false

jobs:
    security_checks:
        runs-on: ubuntu-latest
        steps:

            - name: Checkout code
              uses: actions/checkout@v4

            - name: Gitleaks installation
              run: |
               sudo apt-get update -y
               sudo apt-get install gitleaks -y

            - name: Checking for hardocded vunerabilities in the code
              run: gitleaks detect source . -r gitleaks-report.json -f json

            - name: Installing trivy
              run: |
                sudo apt-get install wget apt-transport-https gnupg lsb-release
                wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
                echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
                sudo apt-get update -y
                sudo apt-get install trivy -y
            
            - name: Trivy FS scan
              run: trivy fs --format table -o fs-report.json .

    build:
        runs-on: ubuntu-latest
        steps:

            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                java-version: '17'
                distribution: 'temurin'
                cache: maven

            - name: Build with Maven
              run: mvn compile

            - name: Making the .jar file into an artifact
              uses: actions/upload-artifact@v4
              with:
                name: maven-artifact
                path: target/*.jar

    test:
        runs-on: ubuntu-latest
        needs: build
        steps:

            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                java-version: '17'
                distribution: 'temurin'
                cache: maven
                
            - name: Running maven tests
              run: mvn test



              # - name: Downloading the maven artifact made in the previous job
            #   uses: actions/download-artifact@v4
            #   with:
            #     name: maven-artifact